### ISSUE TITLE
Thanks for the code i have one question regarding that how to construct the 3d sparse structure from .ply file i tried to open it in a meshlab  but there is no structure and file is empty 

### ISSUE THREAD

**Issue by connectedhealthcaremy** [Tiotao/sam-kit#1]

**Comment by Tiotao** [comment]
Are u trying the example or using your own photo?

**Comment by connectedhealthcaremy** [comment]
i have  tried your example file final.ply and open it in the mesh tool i zoomed in to it i saw the points are there this problem resolved now but when i tried to run your code its giving me an error. Please help in figuring out whats the issue as i am not so much proficient in python i am pasting the log. 
I am facing the compilation error when i am running on the  original dataset

**Comment by connectedhealthcaremy** [comment]
This is the log results
ceres solver: INFO     Start Identifying Corners
ceres solver: INFO     Reference Image: images/0020_still_0002.png
ceres solver: INFO     Identified 41 corners.
ceres solver: INFO     Start Corner Tracking
ceres solver: INFO     Tracking corners in 2 images.
ceres solver: INFO     Finsihed Corner Tracking
ceres solver: INFO     41 corners were found with complete optical flow
ceres solver: INFO     Filter Corners: Homography
ceres solver: INFO     Starting Corners Number:41
ceres solver: INFO     Total Camera Numbers:3
Number of corners
ceres solver: INFO     Result Corner Number: 41
ceres solver: INFO     Finished Homography filtering, updating Corners and Optical Flow
ceres solver: INFO     Update Problem
Traceback (most recent call last):
  File "example.py", line 10, in <module>
    p.track()
  File "../main/objects.py", line 278, in track
    tracker.update_problem(self)
  File "../main/objects.py", line 227, in update_problem
    color = tuple(self.reference_image[position.x-1][position.y+1].tolist())
IndexError: index -1296 is out of bounds for axis 0 with size 1080

**Comment by Tiotao** [comment]
Thanks for the log results. I am currently preparing for another major project, but rest assure that I will take some time into this.

**Comment by connectedhealthcaremy** [comment]
Please help me in this a little bit when you got time. I need help in running the just existing code then the remaining i will sort out myself

**Comment by yuvalg1987** [comment]
Hi, Any update on this issue? I tried running my own image sequence but the code crashes at this point. 
Thanks!
